apiVersion: v1
kind: Secret
metadata:
    name: ghcr
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:bavqoOR3Z4sNpkg3fhObFcHqDyuSEw83ggTzJKUz7qgMTJB+VI0QXRKmoMBLM/awS4AJFNfeY06CK7NI4o6fWdEDhECKErT27MMtSlmPtjquGiNWr1+puE13n1Xq8fofhPCUz8TthfkBkJSd6x7cX4vlBgmoR09hjcrNow1NUybxsnCgF2H/feZjjZ1qIug9bF35KbtFbx3VCLuPLmIuu/LXZbSVrza1M2QkfjJfmns+qOFvXyCKAgGPpwTQCmbU6vVtNynutImao56uFlbcCc5X6sxNHtEEDqt81bvFAk1Nql2Kd0VChjS2DhLIbT7DA+Br5iAgZro=,iv:ws8GMRcRYelM/Qwjd+G0Icbv8aX1W5L8Bva0GSUqKe4=,tag:SBPWMia1h4+bb9jEoI+ZeQ==,type:str]
sops:
    age:
        - recipient: age1xspwcmslwm0dnat5pv8seqxwlcuuc4vjhd2lec69m7qnghmpsf4qdtk49c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWVEvc25QVGcwSnl1NUE5
            cnlaa25nckF1SmIwUEF5L0krMmpmVWQ1M2gwCkU5WHhGUzNjbFRVeDhsaDU0dit1
            UWI0UTd1by9DdkxKYXhPRmg1aEoxLzQKLS0tIDZLckxUWEVVbDUvK3Npdmt2TnFS
            V3VtSE5UZWd1MFFMcW8xZ0RIY1JMSVEKE1r3R8KZ8f4Q8MycNlzDJS1jOT3lsd52
            pDtt0OsQaTpxB90IleR5B8ntbJmV4prmoGL/SJ4lirmXXB/TCq7DbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T16:32:49Z"
    mac: ENC[AES256_GCM,data:JuM9Y/cP/kcU0hfHsARXnhOXwiZ0lR25KtYe5lciFvqgT63cL1A3EosfJE6gUNzNsBJYAUxurEhyMPlJsM1s6Zb+9qRuMJRHfl9LlKwDo0uqnP11jNqRfS4cguC9Ij4DlL/qklEe9Fnr8eJ6jFisYY5pQS1/RhKvwuzq9g4etQs=,iv:rNZM4sllqK1Q6PJfemZivuQ17PaxEvMhekcO6AxCZws=,tag:GN6081KLB8e2+SPRV3mgEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
