configMapGenerator:
  - name: connections
    envs:
      - .connections.env

generatorOptions:
  # you know where to change it if it annoys you later
  disableNameSuffixHash: false
  labels:
    type: generated

resources:
  - aws-bedrock-secret.yml
  - ghcr-secret.yml
  - tls-secret.yml
  - issuer.yml
  - gateway.yml
  - http-route.yml
  - ctfd.yml
  - ctfd-svc.yml
