apiVersion: v1
kind: Secret
metadata:
    name: cert-secret
type: kubernetes.io/tls
data:
    tls.crt: ENC[AES256_GCM,data:GGbdJvKdiFila0pJydsSm6febXoq7fmNC/ktc0iLLQzssfUgefBmlt9y2HImVLBMsyEwqDS4kP35Gj9sZsMUABCo65F7nv3KneOBjfK1WlrdKNKBfLy5erDbrpGluBnxcBdvcF7117lh3acHZi7b/dKqcvjwIFPZiah1l3rG1YXKW2uImxhc+ZVVGel3MInbASNAxQRmiYCIPgF5reXfwKlg7m8m3h3hjVMdLe9Ss9ZimRr3neHKnDYQKZAUGFJHK25k7GsbBgpnW3fRvObs5AhPvZbh86ClZTsKU8fmWf5QOATjj/Ijfxi/FAwLzfi5NG3lo0T2tKKeSqgusTUechVx61Ny7HQR05aINsZaJCsVBmPf3vaXYZpGosaklGaIkOYdRpXqKbcESgSzVL91YpAzrZhE6ruOH/6ZmYJ9AUpHmmf7G5rxI/D37riiUfoOKL/5SMAqYwzVZmUYph0Lu/rllcL7JWNbA6GodIk5J6n8lDHaB5NnW8EiM5GEsUv65+lEIhQvvC2I1fkI5spsvR3LUFFqkxtmta6tya8N/uNW2g8utsku4U0ZSP/rXcxGya3qJcz7lD7zKXpNeLk75IbGZnUnr6kpC8/XaZmNUK8b+lJpi+Jg4xEPKezWgxsC/3uA8/bR3VRvPcaTN0R3++hnal0abSsYMnHmC4osUwBZsWFUNVO9ooKhBfXL7uGyNtLaiIyAQXtnJzzsopDqOsFz56NRrE2X7PGa/gHt8UjgFJ60S7MUh8aiuzdzgxfdwhWlbwcamolcoQq9gK6X32V1+jV2y6wr89U5ri0G2rCJ+jzVXn+SQVpjzINLJg+rlrCWSgM0MKwMbQm1uI9Cb2umB6S0VnzMQysLLc4I06RQCus7YgX3Gdn1FF//msLBKlovZBFcaapKLI/u5q0buesXIuy1VtqjZkyxHmT+mx4iDoVvDiL0/RQH7O1vOeWE,iv:qqxqoJR66+HZnlySbNrxx+n3evE01lnjhLnon8Qu4EM=,tag:L5GRY+sUhnQ63RUoToy2yQ==,type:str]
    tls.key: ENC[AES256_GCM,data:P0uCpW8VgR2pKzuQDUQ8jN31yqu+nCSFLO1YBfcpV1iC8SXHVki7GbKSwaSiF+THxIDtTJMpn0GZo9D2LjnpqEgtZIDmNEOwBrPehj1SXtd2+RKQ/oK3//l4tQSWcGxDkutZ60GlPB5Jzaw0p+GSUs3vAeizuiEen+9Ry8nujLQeE9xwb7WkTQp95hpzKHeTy1oju0EpUbS+/Kp/IDcJ+w==,iv:r9maVpNoiUxnVD4/Gaqt/ag/ZcN/zhKmHXWEqsHRm8g=,tag:8KdY21U6TZVRhieRy4bUiQ==,type:str]
sops:
    age:
        - recipient: age1xspwcmslwm0dnat5pv8seqxwlcuuc4vjhd2lec69m7qnghmpsf4qdtk49c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc3kyQXhmRDc2akhGcjFC
            NzFBY1I1YXJsOTFYN3kySmFmL05nM2Q0RnhFCjhaZHc1a2NVamRvY21hQUxkblhY
            MlUxc3hkY1RsN2FLZ2J3UVZldW5KQkUKLS0tIDdEREVwbEVoTEtrdlMyRi9tdzEw
            YkhKdk9yckRDZHE3dG1ZQklLM09YSWcKRq9L8xOyerWDER7qxI8EkBr2UvtgX+6Y
            I+wkkUF9sx11Px+J98z+PnNuUB340gzbUa6n4kk9DuNqcriqsKkYUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T16:32:57Z"
    mac: ENC[AES256_GCM,data:M8EFzJO1NhmhK8v2imUMI8okIxLGatC8MhgeuJTdszAqqcqzA16X7ZMuxNdgAtOsdD6Wihl3I+dOGXBrpf34LM6mbHZKk/WEpK7yKQ779GRLGmA947Mjfwmi6b//Sbzlxf7I6xgU6nQEIeI3RehnjBS/eskrMbImK8fI88yWWts=,iv:Lks8//q5QgevEeXaalBgWjE0W2hAv/wutpCH2YcqU1k=,tag:rZAmxSE3pYdxfVtv4qjSmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
